include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Blocks

# Core
Blocks_OBJC_FILES += \
	BKExtension.m \
	BKExtensionPoint.m \
	BKLog.m \
	BKPlugin.m \
	BKPluginRegistry.m \
	BKRequirement.m 

ADDITIONAL_OBJCFLAGS += -I../Headers -fobjc-exceptions

include $(GNUSTEP_MAKEFILES)/subproject.make

