include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=BasicPersistence

$(TOOL_NAME)_OBJC_LIBS=-lCoreObject -lEtoileFoundation -lgnustep-gui
$(TOOL_NAME)_OBJC_FILES=main.m

include $(GNUSTEP_MAKEFILES)/tool.make
