include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME=fmdb
fmdb_OBJC_FILES=\
	src/FMDatabaseAdditions.m \
	src/FMDatabase.m \
	src/FMResultSet.m 

fmdb_CPPFLAGS=-I..

include $(GNUSTEP_MAKEFILES)/subproject.make
